### ISSUE TITLE
Is it possible to get the score returned

### ISSUE THREAD

**Issue by swilla** [oneduo/laravel-recaptcha-enterprise#17]
I want to store this in the database to see the score someone received while registering. If I try and "re-assess" the token after validation it gives me an error "DUPE".  Is there a way around this or to append it to the request after validation?

**Comment by Rezrazi** [comment]
Hi
Yeah I think tokens are meant to be single use.

For your use case (I don't know if it will work) but you might want to try binding your own `\Oneduo\RecaptchaEnterprise\Services\RecaptchaService`

By binding a new implementation that extends the base class, and overrides the `assess()` method

https://github.com/oneduo/laravel-recaptcha-enterprise/blob/7708513ab9ab2c82c0f2931c7e946cdf14cdfb2e/src/Services/RecaptchaService.php#L85-L86


and perhaps dispatch an event (to be able to listen to it sync/async)
```php
event(new RecaptchaAssessmentScoreEvent($this->score));
```

and then from within a listener save it to a database
