### ISSUE TITLE
Localization does not work in Laravel 11

### ISSUE THREAD

**Issue by androidacy-user** [oneduo/laravel-recaptcha-enterprise#23]
Hello! When an error occurs, instead of any actual message, we get the following returned:

```json
"errors":{"g-recaptcha-response":["recaptcha-enterprise::validation.recaptcha"]}
```

This makes it very hard to diagnose why it's failing.

**Comment by Rezrazi** [comment]
Thank you for reporting this @androidacy-user 

It was indeed a missing folder for the locale, should be fixed in the next release
