### ISSUE TITLE
Configuration file not publishable

### ISSUE THREAD

**Issue by gogl92** [oneduo/laravel-recaptcha-enterprise#3]
After I installed the package, when I try to run the command:

`artisan vendor:publish --tag="laravel-recaptcha-enterprise-config"`

I got

`INFO  No publishable resources for tag [laravel-recaptcha-enterprise-config].  `

**Comment by Rezrazi** [comment]
Hi @gogl92 

Thank you for pointing this out, indeed it was a typo, you may run the same command with the following tag `recaptcha-enterprise-config`
