### ISSUE TITLE
Depend on API Key instead of OAuth 2.0 Client IDs

### ISSUE THREAD

**Issue by KhaledLela** [oneduo/laravel-recaptcha-enterprise#7]
can we update config to depend on API Key or OAuth 2.0 Client ID ?

**Comment by Rezrazi** [comment]
Hi

Can you please describe a bit more your use case?

**Comment by KhaledLela** [comment]
Thanks i managed to handle my case and depend on service account key, and integrated with this light wrapper library..
Thanks again for your support and nice library.

**Comment by Rezrazi** [comment]
Glad you figured it out, don't hesitate to reach out in case of any issues/feedback 👍

**Comment by peterbabic** [comment]
> Thanks i managed to handle my case and depend on service account key, and integrated with this light wrapper library.

@KhaledLela could you provide some info about how you managed to do it? I could help other people, since service account file is the preferred way google gives you the credentials.
